						<tr>
								<td width="58%" style="padding: 5px;">
								<h2>O firmie</h2>
								<p align="justify"><b>Top$ecurity</b> jest jedną z wiodących firm świadczących profesjonalne usługi w branży finansowej oraz wskazuje firmom możliwości rozwoju i pomaga im je wykorzystywać. Kilkuletnie doświadczenie pozwala nam zaoferować usługi idealnie spełniające potrzeby naszych Klientów, dzięki szybkiej i fachowej obsłudze. Nasze kompetencje dotychczas doceniło wiele firm z różnych branż.<br> Wychodząc naprzeciw oczekiwaniom Klientów świadczymy m.in. następujące usługi:<br>
								<ul>
										<li> doradztwo finansowe,
										<li> doradztwo podatkowe,
										<li> doradztwo europejskie.
								</ul>
								</td>
								<td width="4%">
								&nbsp;
								</td>
								<td width="38%" style="padding: 5px;">
								<big><b>MISJA:</b></big><br><br>
								<big>Oferowanie wysokiej jakości usług, zrozumienie potrzeb Klienta oraz wskazywanie firmom możliwości rozwoju</big><br><br><p align="justify">Zgodnie z misją firmy, współpracując z naszymi Klientami staramy się dążyć do uzyskania przez naszych Klientów przewagi nad konkurencją zarówno na rynku krajowym, jak i międzynarodowym. Naszym zadaniem jest również przygotować powierzone nam firmy do zmieniających się realiów na rynku. <br><br>
								</td> 
						</tr>
