						<tr>
								<td colspan="3" align="center">
								<h2>Organizacja firmy</h2><br><br><img src="gfx/schemat.gif" alt=""  border=1 style="border-color: black"><br><br><big>KONTAKT:</big><br><br>
								Dyrektor: <b>Jan Nieomylny</b><br>
								z-ca dyr. Dział marketingu: <b>Adam Propaganda</b><br>
								z-ca dyr. Dział audytu i doradztwa: <b>Marian Pomocny</b><br>
								Główna księgowy: <b>Maria Hojna</b><br>
								Główny Informatyk: <b>Marcin Niedoceniany</b><br>
								Kierownik Biura Administracji: <b>Anna Porządnicka</b><br>
								Kierownik Biura Prawnego<b>: Zuza Przebiegła</b><br>
								Email: <a href="mailto:biuro@securitydays.pl">biuro@securitydays.pl</a>
								</td>
						</tr>
