						<tr>
								<td colspan="3" height="30">
								&nbsp;
								</td>
						</tr>
						<tr>
								<td width="36%" style="padding: 5px;" align="center">
								<b>Doradztwo finansowe</b><br>
								Działalność instytucji finansowych podlega szczególnym zasadom opodatkowania. W zakresie aspektów rozwiązań finansowych doradzamy również instytucjom niefinansowym. Pomagamy rozwiązywać kwestie podatkowe związane z pozyskiwaniem finansowania.
								</td>
								<td width="36%" style="padding: 5px;" align="center">
								<b>Doradztwo podatkowe:</b><br>Top$ecurity proponuje wszechstronne doradztwo podatkowe zarówno w przypadku dużych transakcji międzynarodowych, jak i doradztwo w zakresie podatków osobistych.
								</td>
								<td width="28%" style="padding: 5px;" align="center">
								<b>Doradztwo Europejskie:</b><br>Dążąc do jak najlepszego przygotowania przedsiębiorstwa do zmian wynikających z integracji Polski z UE.
								</td>
						</tr>
