						<tr>
								<td colspan="3" align="center"><br><br>
								Firma z branży finansowej "Top$ecurity" poszukuje kandydatów na stanowisko audytora bezpieczeństwa sieci. Firma stanęła przed problemem odpowiedniego zabezpieczenia systemu informatycznego.<br><br>
								Rejestarcja kandydatów:<br><b>od 1 do 10 września 2008</b><br><br>
								Wirtualna firma Top$ecurity czeka na kandydatów !<br><br>

								</td>
						</tr>
