						<tr>
								<td colspan="2" align="left" style="padding: 5px;">
								<A href="index.html?dzial=panel&logout=1">Logout</a>
								</td>
						<tr>
								<td colspan="3" align="left" style="padding: 5px;">
								<h3>Hash</h3>
								Tutaj możecie testować eksperymentalną wersję naszego nowego algorytmu. Jak macie jakiekolwiek uwagi, to przesyłajcie mi je na maila. Janek chce wprowadzić ten algorytm na rynek już w październiku jako następcę MD5!!! - <i>Marcin</i>
								<br><br>
								<form action="index.html?dzial=panel" method="post">
									<input name="str" type="text">
									<input name="hash" type="submit" value="GetHash">
								</form>
								<br>
								</td>
						</tr>
